<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="TestCases.TestCases" tests="3" time="0.000" ignored="0" failures="0" timestamp="03 Mar 2021 08:49:33 GMT" skipped="2" hostname="IND-CHN-LT10552" errors="1">
  <testcase name="TC_tenantLogin" time="0.000" classname="TestCases.TestCases">
    <skipped/>
  </testcase> <!-- TC_tenantLogin -->
  <testcase name="TC_tenantRegistration" time="0.000" classname="TestCases.TestCases">
    <skipped/>
  </testcase> <!-- TC_tenantRegistration -->
  <testcase name="precondition" time="0.000" classname="TestCases.TestCases">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.GenericKeywords.captureScreenShot(GenericKeywords.java:2466)
	at automationFramework.GenericKeywords.testStepFailed(GenericKeywords.java:2504)
	at automationFramework.GenericKeywords.openBrowser(GenericKeywords.java:609)
	at baseClass.BaseClass.setup(BaseClass.java:29)
	at TestCases.TestCases.precondition(TestCases.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- precondition -->
</testsuite> <!-- TestCases.TestCases -->
